name: eCalendar
version: "1.0.5"
slug: ecalendar
description: Daily planner - events, chores, lists, weather
arch:
  - aarch64
  - amd64
init: true
ingress: true
ports: {}
ports_description: {}
options: {}
schema: {}
