name: eCalendar (matt-gun)
version: "1.0.7"
slug: ecalendar-matt
description: Daily planner - events, chores, lists, weather
arch:
  - aarch64
  - amd64
init: false
ingress: true
ports: {}
ports_description: {}
options: {}
schema: {}
